import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Image from "next/image";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header>
          <nav className="bg-white border-gray-200 px-4 py-2.5 dark:bg-gray-800">
            <div className="flex flex-wrap justify-between items-center mx-auto">
              <Link href="/" className="flex items-center">
                <Image
                  src="/logo.png"
                  alt="Metalix Enterprise Logo"
                  className="w-50 h-auto"
                  width={500}
                  height={500}
                />
              </Link>
            </div>
          </nav>
        </header>
        {children}
      </body>
    </html>
  );
}
