export const clients = [
  {
    id: 1,
    name: "ABC Pvt Ltd",
    gstNo: "27ABCDE1234F1Z5",
    email: "contact@abc.com",
    phone: "9876543210",
    address: {
      area: "MG Road",
      pincode: 400001,
      state: "Maharashtra",
      country: "India",
    },
  },
  {
    id: 2,
    name: "XYZ Enterprises",
    gstNo: "29XYZEF5678G2Z6",
    email: "info@xyz.com",
    phone: "9123456789",
    address: {
      area: "Brigade Road",
      pincode: 560001,
      state: "Karnataka",
      country: "India",
    },
  },
  {
    id: 3,
    name: "Global Tech",
    gstNo: "33GLOBH9012H3Z7",
    email: "support@globaltech.com",
    phone: "9988776655",
    address: {
      area: "Anna Salai",
      pincode: 600002,
      state: "Tamil Nadu",
      country: "India",
    },
  },
  {
    id: 4,
    name: "Tech Innovators",
    gstNo: "24TECHI3456J4Z8",
    email: "hello@techinnovators.com",
    phone: "9871234567",
    address: {
      area: "Sector 21",
      pincode: 122001,
      state: "Haryana",
      country: "India",
    },
  },
  {
    id: 5,
    name: "NextGen Solutions",
    gstNo: "27NEXTG7890K5Z9",
    email: "contact@nextgensolutions.com",
    phone: "9812345678",
    address: {
      area: "Bandra West",
      pincode: 400050,
      state: "Maharashtra",
      country: "India",
    },
  },
  {
    id: 6,
    name: "Alpha Corp",
    gstNo: "27ALPHA1234L6Z0",
    email: "info@alphacorp.com",
    phone: "9876543211",
    address: {
      area: "Marine Drive",
      pincode: 400002,
      state: "Maharashtra",
      country: "India",
    },
  },
  {
    id: 7,
    name: "Beta Solutions",
    gstNo: "29BETA5678M7Z1",
    email: "contact@betasolutions.com",
    phone: "9123456790",
    address: {
      area: "MG Road",
      pincode: 560002,
      state: "Karnataka",
      country: "India",
    },
  },
  {
    id: 8,
    name: "Gamma Innovations",
    gstNo: "33GAMMA9012N8Z2",
    email: "support@gammainnovations.com",
    phone: "9988776656",
    address: {
      area: "T Nagar",
      pincode: 600003,
      state: "Tamil Nadu",
      country: "India",
    },
  },
  {
    id: 9,
    name: "Delta Enterprises",
    gstNo: "24DELTA3456O9Z3",
    email: "hello@deltaenterprises.com",
    phone: "9871234568",
    address: {
      area: "DLF Phase 3",
      pincode: 122002,
      state: "Haryana",
      country: "India",
    },
  },
  {
    id: 10,
    name: "Epsilon Tech",
    gstNo: "27EPSIL7890P0Z4",
    email: "contact@epsilontech.com",
    phone: "9812345679",
    address: {
      area: "Andheri East",
      pincode: 400051,
      state: "Maharashtra",
      country: "India",
    },
  },
  {
    id: 11,
    name: "Zeta Systems",
    gstNo: "27ZETA1234Q1Z5",
    email: "info@zetasystems.com",
    phone: "9876543212",
    address: {
      area: "Churchgate",
      pincode: 400003,
      state: "Maharashtra",
      country: "India",
    },
  },
  {
    id: 12,
    name: "Eta Solutions",
    gstNo: "29ETA5678R2Z6",
    email: "contact@etasolutions.com",
    phone: "9123456791",
    address: {
      area: "Indiranagar",
      pincode: 560003,
      state: "Karnataka",
      country: "India",
    },
  },
  {
    id: 13,
    name: "Theta Innovations",
    gstNo: "33THETA9012S3Z7",
    email: "support@thetainnovations.com",
    phone: "9988776657",
    address: {
      area: "Velachery",
      pincode: 600004,
      state: "Tamil Nadu",
      country: "India",
    },
  },
  {
    id: 14,
    name: "Iota Enterprises",
    gstNo: "24IOTA3456T4Z8",
    email: "hello@iotaenterprises.com",
    phone: "9871234569",
    address: {
      area: "Cyber City",
      pincode: 122003,
      state: "Haryana",
      country: "India",
    },
  },
  {
    id: 15,
    name: "Kappa Tech",
    gstNo: "27KAPPA7890U5Z9",
    email: "contact@kappatech.com",
    phone: "9812345680",
    address: {
      area: "Powai",
      pincode: 400052,
      state: "Maharashtra",
      country: "India",
    },
  },
  {
    id: 16,
    name: "Lambda Corp",
    gstNo: "27LAMBDA1234V6Z0",
    email: "info@lambdacorp.com",
    phone: "9876543213",
    address: {
      area: "Nariman Point",
      pincode: 400004,
      state: "Maharashtra",
      country: "India",
    },
  },
  {
    id: 17,
    name: "Mu Solutions",
    gstNo: "29MU5678W7Z1",
    email: "contact@musolutions.com",
    phone: "9123456792",
    address: {
      area: "Koramangala",
      pincode: 560004,
      state: "Karnataka",
      country: "India",
    },
  },
  {
    id: 18,
    name: "Nu Innovations",
    gstNo: "33NU9012X8Z2",
    email: "support@nuinnovations.com",
    phone: "9988776658",
    address: {
      area: "Adyar",
      pincode: 600005,
      state: "Tamil Nadu",
      country: "India",
    },
  },
  {
    id: 19,
    name: "Xi Enterprises",
    gstNo: "24XI3456Y9Z3",
    email: "hello@xienterprises.com",
    phone: "9871234570",
    address: {
      area: "Udyog Vihar",
      pincode: 122004,
      state: "Haryana",
      country: "India",
    },
  },
  {
    id: 20,
    name: "Omicron Tech",
    gstNo: "27OMICR7890Z0Z4",
    email: "contact@omicrontech.com",
    phone: "9812345681",
    address: {
      area: "Juhu",
      pincode: 400053,
      state: "Maharashtra",
      country: "India",
    },
  },
  {
    id: 21,
    name: "Pi Corp",
    gstNo: "27PI1234A1Z5",
    email: "info@picorp.com",
    phone: "9876543214",
    address: {
      area: "Colaba",
      pincode: 400005,
      state: "Maharashtra",
      country: "India",
    },
  },
  {
    id: 22,
    name: "Rho Solutions",
    gstNo: "29RHO5678B2Z6",
    email: "contact@rhosolutions.com",
    phone: "9123456793",
    address: {
      area: "Whitefield",
      pincode: 560005,
      state: "Karnataka",
      country: "India",
    },
  },
  {
    id: 23,
    name: "Sigma Innovations",
    gstNo: "33SIGMA9012C3Z7",
    email: "support@sigmainnovations.com",
    phone: "9988776659",
    address: {
      area: "Guindy",
      pincode: 600006,
      state: "Tamil Nadu",
      country: "India",
    },
  },
  {
    id: 24,
    name: "Tau Enterprises",
    gstNo: "24TAU3456D4Z8",
    email: "hello@tauenterprises.com",
    phone: "9871234571",
    address: {
      area: "Manesar",
      pincode: 122005,
      state: "Haryana",
      country: "India",
    },
  },
  {
    id: 25,
    name: "Upsilon Tech",
    gstNo: "27UPSIL7890E5Z9",
    email: "contact@upsilontech.com",
    phone: "9812345682",
    address: {
      area: "Malad West",
      pincode: 400054,
      state: "Maharashtra",
      country: "India",
    },
  },
];
